<template>
  <div :class="classes">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      xmlns:xlink="http://www.w3.org/1999/xlink"
      style="
        margin: auto;
        background: rgb(255, 255, 255);
        display: block;
        shape-rendering: auto;
      "
      width="230px"
      height="230px"
      viewBox="0 0 100 100"
      preserveAspectRatio="xMidYMid"
    >
      <rect x="22" y="22" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="41" y="22" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0.1923076923076923s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="60" y="22" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0.3846153846153846s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="22" y="41" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="1.346153846153846s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="60" y="41" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0.5769230769230769s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="22" y="60" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="1.1538461538461537s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="41" y="60" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0.9615384615384615s"
          calcMode="discrete"
        ></animate>
      </rect>
      <rect x="60" y="60" width="18" height="18" fill="#add8e6">
        <animate
          attributeName="fill"
          values="#daa520;#add8e6;#add8e6"
          keyTimes="0;0.125;1"
          dur="1.5384615384615383s"
          repeatCount="indefinite"
          begin="0.7692307692307692s"
          calcMode="discrete"
        ></animate>
      </rect>
      <!-- [ldio] generated by https://loading.io/ -->
    </svg>
  </div>
</template>
<script>
export default {
  props: {
    isProcessing: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    classes() {
      return `loading ${this.isProcessing ? "" : "hidden"}`;
    },
  },
};
</script>
<style scoped>
.loading {
  position: absolute;
  left: 50%;
  transform: translateX(-50%);
  top: 100%;
  z-index: 5;
}
.hidden {
  display: none;
}
</style>